// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Buffer is a text tab's in-memory snapshot. SavedContent is the baseline
 * for dirty checks; Content may contain edits that have never reached disk.
 * ID changes on close/reopen so a late update cannot resurrect an old tab.
 */
export interface Buffer {
    "id": string;
    "content": string;
    "savedContent": string;
    "version": number;
}
