// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../encoding/json/models.js";

export interface DocumentSymbol {
    "name": string;
    "kind": number;
    "range": Range;
    "selectionRange": Range;
    "children"?: (DocumentSymbol | null)[] | null;
}

export interface Hover {
    "contents": json$0.RawMessage;
}

export interface Location {
    "uri": string;
    "range": Range;
}

/**
 * Basic protocol structures. Positions are (line, character) pairs with
 * UTF-16 code unit characters — which matches CodeMirror's native offsets,
 * so the frontend can pass offsets straight through.
 */
export interface Position {
    "line": number;
    "character": number;
}

export interface Range {
    "start": Position;
    "end": Position;
}
