// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileMatches groups the matches found in one file (absolute path).
 */
export interface FileMatches {
    "path": string;
    "matches": Match[] | null;
}

/**
 * Match is one hit inside a file. Line is 1-based; Col is the 1-based byte
 * offset of the match start within the line (approximate for multi-byte
 * unicode when case folding shifts byte offsets — acceptable MVP). Text is
 * the full line capped at 200 bytes.
 */
export interface Match {
    "line": number;
    "col": number;
    "text": string;
}

/**
 * Result is the aggregate outcome of one search.
 */
export interface Result {
    "files": number;
    "matches": number;
    "filesMatches": FileMatches[] | null;
    "truncated": boolean;
}
