// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the main service bound to the UI. Pure facade over engines;
 * all engine state is per-project, namespaced by Project.ID.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as project$0 from "./project/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CloseWatcher stops and releases the watcher for projectID.
 */
export function CloseWatcher(projectID: string): $CancellablePromise<void> {
    return $Call.ByID(250663456, projectID);
}

/**
 * ForgetRecent drops a recents entry by root path.
 */
export function ForgetRecent(root: string): $CancellablePromise<void> {
    return $Call.ByID(1919972942, root);
}

/**
 * ListProjects returns currently open projects, most recently used first.
 */
export function ListProjects(): $CancellablePromise<project$0.Project[] | null> {
    return $Call.ByID(1843757078);
}

/**
 * ListTree walks root recursively to maxTreeDepth, dirs-first sorted, skipping
 * dotfiles except .env, .gitignore and .github.
 */
export function ListTree(root: string): $CancellablePromise<$models.Entry[] | null> {
    return $Call.ByID(1338655484, root);
}

/**
 * OpenProject registers the project, remembers it in recents, starts a
 * filesystem watcher and emits "project.added". Watcher events are re-emitted
 * as "fs.change" with {projectId, path, op}.
 */
export function OpenProject(root: string): $CancellablePromise<project$0.Project> {
    return $Call.ByID(2520723113, root);
}

/**
 * ReadFile returns file content, refusing files larger than maxFileSize.
 */
export function ReadFile(path: string): $CancellablePromise<string> {
    return $Call.ByID(2211313038, path);
}

/**
 * RecentProjects returns the persisted recents list.
 */
export function RecentProjects(): $CancellablePromise<project$0.Recent[] | null> {
    return $Call.ByID(1503067661);
}

/**
 * RemoveProject closes the project: registry removal, watcher shutdown and
 * "project.removed" emission.
 */
export function RemoveProject(id: string): $CancellablePromise<void> {
    return $Call.ByID(1659478425, id);
}

/**
 * SaveFile persists content via editor.Service (atomic write + dirty tracking).
 */
export function SaveFile(path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(3028267559, path, content);
}
