// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the main service bound to the UI. Pure facade over engines;
 * all engine state is per-project, namespaced by Project.ID.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as acp$0 from "./acp/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agentstore$0 from "./agentstore/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as git$0 from "./git/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as project$0 from "./project/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ACPHarnesses lists known agent profiles with PATH availability.
 */
export function ACPHarnesses(): $CancellablePromise<acp$0.Info[] | null> {
    return $Call.ByID(334792292);
}

/**
 * ACPLoadTranscript returns the persisted chat entries for the project (used
 * by the Agent panel on mount).
 */
export function ACPLoadTranscript(projectID: string): $CancellablePromise<agentstore$0.Entry[] | null> {
    return $Call.ByID(3899692018, projectID);
}

/**
 * ACPNewSession closes the current harness connection and spawns a fresh
 * session with the same harness. The transcript is kept; a divider note entry
 * marks the boundary.
 * 
 * Get + close + spawn are serialized under a.mu together with claimStart, so a
 * concurrent ACPStart / ACPStop cannot interleave: the closed session is never
 * resurrected by a stale-closed send, and only one spawn is in flight.
 */
export function ACPNewSession(projectID: string): $CancellablePromise<void> {
    return $Call.ByID(1433866094, projectID);
}

/**
 * ACPRespondPermission resolves a pending permission request: optionId picks
 * one of the offered options; cancel=true answers {"outcome":"cancelled"}.
 */
export function ACPRespondPermission(projectID: string, requestID: string, optionID: string, cancel: boolean): $CancellablePromise<void> {
    return $Call.ByID(2524187014, projectID, requestID, optionID, cancel);
}

/**
 * ACPSendPrompt runs one synchronous prompt turn: the user entry is persisted
 * and emitted up front, session/update notifications stream out as acp.msg /
 * acp.tool events while the turn is open, and the assembled agent reply is
 * persisted once the turn completes.
 */
export function ACPSendPrompt(projectID: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(1900935072, projectID, text);
}

/**
 * ACPStart resolves the harness profile and spawns one ACP session for the
 * project (one session/connection MVP). After start the persisted transcript
 * is emitted (acp.transcript) followed by an idle state.
 */
export function ACPStart(projectID: string, harnessName: string): $CancellablePromise<void> {
    return $Call.ByID(2977661344, projectID, harnessName);
}

/**
 * ACPStop closes the harness connection (terminating the child process) and
 * reports harness-down.
 */
export function ACPStop(projectID: string): $CancellablePromise<void> {
    return $Call.ByID(1604775396, projectID);
}

/**
 * CloseWatcher stops and releases the watcher for projectID and marks the
 * project closed so the forwarder suppresses any buffered events.
 */
export function CloseWatcher(projectID: string): $CancellablePromise<void> {
    return $Call.ByID(250663456, projectID);
}

/**
 * CloseWelcome hides the welcome window after a project has been opened.
 */
export function CloseWelcome(): $CancellablePromise<void> {
    return $Call.ByID(3084079084);
}

/**
 * EnsureWorkspaceWindow opens the workspace window if none exists (or shows
 * the existing one). Called by the frontend after opening a project.
 */
export function EnsureWorkspaceWindow(): $CancellablePromise<void> {
    return $Call.ByID(2539716435);
}

/**
 * ForgetRecent drops a recents entry by root path.
 */
export function ForgetRecent(root: string): $CancellablePromise<void> {
    return $Call.ByID(1919972942, root);
}

/**
 * GitBranches lists local branches (refs/heads, sorted, short names).
 */
export function GitBranches(projectID: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(133901168, projectID);
}

/**
 * GitCheckout switches worktree to the given local branch.
 */
export function GitCheckout(projectID: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(1882087752, projectID, name);
}

/**
 * GitCommit commits staged changes with the fixed "aide <aide@local>" identity.
 */
export function GitCommit(projectID: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(1431541081, projectID, message);
}

/**
 * GitCreateBranch creates a branch pointing at the current HEAD.
 */
export function GitCreateBranch(projectID: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(906079848, projectID, name);
}

/**
 * GitDiff returns the diff for path against HEAD (staged) or the index (unstaged).
 */
export function GitDiff(projectID: string, path: string, staged: boolean): $CancellablePromise<git$0.DiffPatch> {
    return $Call.ByID(1243866939, projectID, path, staged);
}

/**
 * GitLog returns the n most recent commit entries walking first-parent from HEAD.
 */
export function GitLog(projectID: string, n: number): $CancellablePromise<git$0.LogEntry[] | null> {
    return $Call.ByID(1411275054, projectID, n);
}

/**
 * GitStage adds files to the index ("add"; deleted files are recorded via "rm").
 */
export function GitStage(projectID: string, paths: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(670803978, projectID, paths);
}

/**
 * GitStatus returns Staged/Unstaged/Untracked changes plus the current branch.
 */
export function GitStatus(projectID: string): $CancellablePromise<git$0.Status> {
    return $Call.ByID(2530301110, projectID);
}

/**
 * GitUnstage resets paths back out of the index.
 */
export function GitUnstage(projectID: string, paths: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(1116628283, projectID, paths);
}

/**
 * IndexFiles returns all file paths under root (absolute), walking the full
 * tree recursively. Skips .git, node_modules, dist, build, vendor, target and
 * .next directories, plus all other dotfiles; capped at maxIndexFiles.
 * Phase 6 (tree-sitter index) replaces this walk.
 */
export function IndexFiles(root: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(2535220543, root);
}

/**
 * ListProjects returns currently open projects, most recently used first.
 */
export function ListProjects(): $CancellablePromise<project$0.Project[] | null> {
    return $Call.ByID(1843757078);
}

/**
 * ListTree walks root recursively to maxTreeDepth, dirs-first sorted, skipping
 * dotfiles except .env, .gitignore and .github.
 */
export function ListTree(root: string): $CancellablePromise<$models.Entry[] | null> {
    return $Call.ByID(1338655484, root);
}

/**
 * OpenProject registers the project, remembers it in recents, starts a
 * filesystem watcher and emits "project.added". Watcher events are re-emitted
 * as "fs.change" with {projectId, path, op}.
 */
export function OpenProject(root: string): $CancellablePromise<project$0.Project> {
    return $Call.ByID(2520723113, root);
}

/**
 * PickFolder opens a native folder-picker and returns the chosen absolute
 * path, or an empty string if the user cancelled the dialog.
 */
export function PickFolder(): $CancellablePromise<string> {
    return $Call.ByID(588397301);
}

/**
 * ReadFile returns file content, refusing files larger than maxFileSize.
 */
export function ReadFile(path: string): $CancellablePromise<string> {
    return $Call.ByID(2211313038, path);
}

/**
 * RecentProjects returns the persisted recents list.
 */
export function RecentProjects(): $CancellablePromise<project$0.Recent[] | null> {
    return $Call.ByID(1503067661);
}

/**
 * RemoveProject closes the project: registry removal, watcher shutdown and
 * "project.removed" emission.
 */
export function RemoveProject(id: string): $CancellablePromise<void> {
    return $Call.ByID(1659478425, id);
}

/**
 * SaveFile persists content via editor.Service (atomic write + dirty tracking).
 */
export function SaveFile(path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(3028267559, path, content);
}
