// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Entry is a node in a project tree listing. Path is absolute.
 */
export interface Entry {
    "name": string;
    "path": string;
    "dir": boolean;
}
