// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Entry is one transcript row. Tool entries upsert by ToolID within a
 * session, so a status change replaces rather than appends.
 */
export interface Entry {
    "role": string;
    "text": string;
    "toolId"?: string;
    "kind": string;
    "status"?: string;
    "when": string;
}

/**
 * SessionMeta describes one persisted session.
 */
export interface SessionMeta {
    "id": string;
    "projectId": string;
    "title": string;
    "created": string;
    "updated": string;
    "messageCount": number;
}
