// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Entry is one line of a project's chat transcript.
 */
export interface Entry {
    "role": string;
    "text": string;
    "toolId"?: string;
    "kind": string;
    "when": string;
}
