// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Info describes one launchable ACP agent profile.
 */
export interface Info {
    "name": string;
    "command": string[] | null;
    "available": boolean;
}
