// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Project {
    /**
     * uuid
     */
    "id": string;
    "name": string;
    "root": string;
    "branch": string;
    "lastUsed": string;
    "engineOk": boolean;
}

export interface Recent {
    "id": string;
    "root": string;
    "branch": string;
    "lastUsed": string;
}
