// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Project {
    /**
     * uuid
     */
    "id": string;
    "name": string;
    "root": string;
    "branch": string;
    "lastUsed": string;
    "engineOk": boolean;

    /** Creates a new Project instance. */
    constructor($$source: Partial<Project> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("root" in $$source)) {
            this["root"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("lastUsed" in $$source)) {
            this["lastUsed"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("engineOk" in $$source)) {
            this["engineOk"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Project instance from a string or object.
     */
    static createFrom($$source: any = {}): Project {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Project($$parsedSource as Partial<Project>);
    }
}

export class Recent {
    "id": string;
    "root": string;
    "branch": string;
    "lastUsed": string;

    /** Creates a new Recent instance. */
    constructor($$source: Partial<Recent> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("root" in $$source)) {
            this["root"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("lastUsed" in $$source)) {
            this["lastUsed"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Recent instance from a string or object.
     */
    static createFrom($$source: any = {}): Recent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Recent($$parsedSource as Partial<Recent>);
    }
}
